In [2]:
import pandas as pd
import numpy as np

In [3]:
customers = pd.read_csv("blinkit_customers.csv")
orders = pd.read_csv("blinkit_orders.csv")
products = pd.read_csv("blinkit_products.csv")
order_items = pd.read_csv("blinkit_order_items.csv")
inventory = pd.read_csv("blinkit_inventory.csv")
delivery = pd.read_csv("blinkit_delivery_performance.csv")
feedback = pd.read_csv("blinkit_customer_feedback.csv")
marketing = pd.read_csv("blinkit_marketing_performance.csv")

# Customer Table Analysis

In [13]:
import pandas as pd
import numpy as np

customers = pd.read_csv("blinkit_customers.csv")

# Basic Information
customers.info()
customers.describe(include="all")

# Check Shape
customers.shape

# Missing Values
customers.isnull().sum()

# Duplicate Rows
customers.duplicated().sum()

# Duplicate Customer IDs
customers["customer_id"].duplicated().sum()

# Remove Duplicate Rows
customers.drop_duplicates(inplace=True)

# Registration Date
customers["registration_date"] = pd.to_datetime(
    customers["registration_date"],
    errors="coerce"
)

# Fill Missing Customer Segment
customers["customer_segment"] = customers["customer_segment"].fillna("Unknown")

# Total Orders
customers["total_orders"] = customers["total_orders"].fillna(0)

# Average Order Value
customers["avg_order_value"] = customers["avg_order_value"].fillna(
    customers["avg_order_value"].median()
)

# Pincode should be String
customers["pincode"] = customers["pincode"].astype(str)

# Feature Engineering
customers["registration_year"] = customers["registration_date"].dt.year
customers["registration_month"] = customers["registration_date"].dt.month_name()
customers["phone"] = customers["phone"].astype(str)
customers["customer_segment"] = customers["customer_segment"].astype("category")
month_order = [
    "January","February","March","April","May","June",
    "July","August","September","October","November","December"
]

customers["registration_month"] = pd.Categorical(
    customers["registration_month"],
    categories=month_order,
    ordered=True
)
customers.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        2500 non-null   int64
 1   customer_name      2500 non-null   object
 2   email              2500 non-null   object
 3   phone              2500 non-null   int64
 4   address            2500 non-null   object
 5   area               2500 non-null   object
 6   pincode            2500 non-null   int64
 7   registration_date  2500 non-null   object
 8   customer_segment   2500 non-null   object
 9   total_orders       2500 non-null   int64
 10  avg_order_value    2500 non-null   float64
dtypes: float64(1), int64(4), object(6)
memory usage: 215.0+ KB

,customer_id,customer_name,email,phone,address,area,pincode,registration_date,customer_segment,total_orders,avg_order_value,registration_year,registration_month
0,97475543,Niharika Nagi,ektataneja@example.org,912987579691,"23, Nayar Path, Bihar Sharif-154625",Udupi,321865,2023-05-13,Premium,13,451.92,2023,May
1,22077605,Megha Sachar,vedant45@example.com,915123179717,"51/302, Buch Chowk\nSrinagar-570271",Aligarh,149394,2024-06-18,Inactive,4,825.48,2024,June
2,47822591,Hema Bahri,samiazaan@example.com,910034076149,"941\nAnne Street, Darbhanga 186125",Begusarai,621411,2024-09-25,Regular,17,1969.81,2024,September
3,79726146,Zaitra Vig,ishanvi87@example.org,916264232390,"43/94, Ghosh, Alappuzha 635655",Kozhikode,826054,2023-10-04,New,4,220.09,2023,October
4,57102800,Januja Verma,atideshpande@example.org,917293526596,"06\nOm, Ambarnath 477463",Ichalkaranji,730539,2024-03-22,Inactive,14,578.14,2024,March

In [14]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customer_id         2500 non-null   int64
 1   customer_name       2500 non-null   object
 2   email               2500 non-null   object
 3   phone               2500 non-null   object
 4   address             2500 non-null   object
 5   area                2500 non-null   object
 6   pincode             2500 non-null   object
 7   registration_date   2500 non-null   datetime64[ns]
 8   customer_segment    2500 non-null   category
 9   total_orders        2500 non-null   int64
 10  avg_order_value     2500 non-null   float64
 11  registration_year   2500 non-null   int32
 12  registration_month  2500 non-null   category
dtypes: category(2), datetime64[ns](1), float64(1), int32(1), int64(2), object(6)
memory usage: 210.7+ KB

In [5]:
customers.isnull().sum()

customer_id          0
customer_name        0
email                0
phone                0
address              0
area                 0
pincode              0
registration_date    0
customer_segment     0
total_orders         0
avg_order_value      0
dtype: int64

In [55]:
customers.to_csv(
    "cleaned_customers.csv",
    index=False
)

# Orders Table Analysis

In [15]:
orders.head()

,order_id,customer_id,order_date,promised_delivery_time,actual_delivery_time,delivery_status,order_total,payment_method,delivery_partner_id,store_id
0,1961864118,30065862,2024-07-17 08:34:01,2024-07-17 08:52:01,2024-07-17 08:47:01,On Time,3197.07,Cash,63230,4771
1,1549769649,9573071,2024-05-28 13:14:29,2024-05-28 13:25:29,2024-05-28 13:27:29,On Time,976.55,Cash,14983,7534
2,9185164487,45477575,2024-09-23 13:07:12,2024-09-23 13:25:12,2024-09-23 13:29:12,On Time,839.05,UPI,39859,9886
3,9644738826,88067569,2023-11-24 16:16:56,2023-11-24 16:34:56,2023-11-24 16:33:56,On Time,440.23,Card,61497,7917
4,5427684290,83298567,2023-11-20 05:00:39,2023-11-20 05:17:39,2023-11-20 05:18:39,On Time,2526.68,Cash,84315,2741

In [16]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   order_id                5000 non-null   int64
 1   customer_id             5000 non-null   int64
 2   order_date              5000 non-null   object
 3   promised_delivery_time  5000 non-null   object
 4   actual_delivery_time    5000 non-null   object
 5   delivery_status         5000 non-null   object
 6   order_total             5000 non-null   float64
 7   payment_method          5000 non-null   object
 8   delivery_partner_id     5000 non-null   int64
 9   store_id                5000 non-null   int64
dtypes: float64(1), int64(4), object(5)
memory usage: 390.8+ KB

In [5]:
orders.isnull().sum()

order_id                  0
customer_id               0
order_date                0
promised_delivery_time    0
actual_delivery_time      0
delivery_status           0
order_total               0
payment_method            0
delivery_partner_id       0
store_id                  0
dtype: int64

In [17]:
orders.drop_duplicates(inplace=True)

In [18]:
orders.dtypes

order_id                    int64
customer_id                 int64
order_date                 object
promised_delivery_time     object
actual_delivery_time       object
delivery_status            object
order_total               float64
payment_method             object
delivery_partner_id         int64
store_id                    int64
dtype: object

In [19]:
date_columns = [
    "order_date",
    "promised_delivery_time",
    "actual_delivery_time"
]

for col in date_columns:
    orders[col] = pd.to_datetime(orders[col], errors="coerce")

In [20]:
orders["payment_method"] = (
    orders["payment_method"]
    .str.strip()
    .str.title()
)

orders["delivery_status"] = (
    orders["delivery_status"]
    .str.strip()
    .str.title()
)

In [21]:
orders["delivery_status"].unique()

array(['On Time', 'Slightly Delayed', 'Significantly Delayed'],
      dtype=object)

In [22]:
orders["payment_method"].unique()

array(['Cash', 'Upi', 'Card', 'Wallet'], dtype=object)

In [23]:
orders["order_total"] = orders["order_total"].abs()

In [25]:
orders["order_year"] = orders["order_date"].dt.year
orders["order_month"] = orders["order_date"].dt.month_name()
orders["weekday"] = orders["order_date"].dt.day_name()

In [26]:
orders["customer_id"].isin(customers["customer_id"]).all()

True

In [28]:
orders.head()

,order_id,customer_id,order_date,promised_delivery_time,actual_delivery_time,delivery_status,order_total,payment_method,delivery_partner_id,store_id,order_year,order_month,weekday
0,1961864118,30065862,2024-07-17 08:34:01,2024-07-17 08:52:01,2024-07-17 08:47:01,On Time,3197.07,Cash,63230,4771,2024,July,Wednesday
1,1549769649,9573071,2024-05-28 13:14:29,2024-05-28 13:25:29,2024-05-28 13:27:29,On Time,976.55,Cash,14983,7534,2024,May,Tuesday
2,9185164487,45477575,2024-09-23 13:07:12,2024-09-23 13:25:12,2024-09-23 13:29:12,On Time,839.05,Upi,39859,9886,2024,September,Monday
3,9644738826,88067569,2023-11-24 16:16:56,2023-11-24 16:34:56,2023-11-24 16:33:56,On Time,440.23,Card,61497,7917,2023,November,Friday
4,5427684290,83298567,2023-11-20 05:00:39,2023-11-20 05:17:39,2023-11-20 05:18:39,On Time,2526.68,Cash,84315,2741,2023,November,Monday

In [56]:
orders.to_csv(
    "cleaned_orders.csv",
    index=False
)

# Products Table Analysis

In [29]:
products.head()

,product_id,product_name,category,brand,price,mrp,margin_percentage,shelf_life_days,min_stock_level,max_stock_level
0,153019,Onions,Fruits & Vegetables,Aurora LLC,947.95,1263.93,25.0,3,13,88
1,11422,Potatoes,Fruits & Vegetables,Ramaswamy-Tata,127.16,169.55,25.0,3,20,65
2,669378,Potatoes,Fruits & Vegetables,Chadha and Sons,212.14,282.85,25.0,3,23,70
3,848226,Tomatoes,Fruits & Vegetables,Barad and Sons,209.59,279.45,25.0,3,10,51
4,890623,Onions,Fruits & Vegetables,"Sangha, Nagar and Varty",354.52,472.69,25.0,3,27,55

In [30]:
products.isnull().sum()

product_id           0
product_name         0
category             0
brand                0
price                0
mrp                  0
margin_percentage    0
shelf_life_days      0
min_stock_level      0
max_stock_level      0
dtype: int64

In [31]:
products.drop_duplicates(inplace=True)

In [32]:
products.dtypes

product_id             int64
product_name          object
category              object
brand                 object
price                float64
mrp                  float64
margin_percentage    float64
shelf_life_days        int64
min_stock_level        int64
max_stock_level        int64
dtype: object

In [33]:
text_columns = [
    "product_name",
    "category",
    "brand"
]

for col in text_columns:
    products[col] = products[col].str.strip()

In [34]:
products["category"] = products["category"].str.title()
products["brand"] = products["brand"].str.title()

In [36]:
products["brand"].unique()

array(['Aurora Llc', 'Ramaswamy-Tata', 'Chadha And Sons',
       'Barad And Sons', 'Sangha, Nagar And Varty',
       'Doshi, Sarraf And Sama', 'Ramakrishnan-Ghose', 'Agarwal-Dhar',
       'Suresh, Bose And Bajwa', 'Mandal-Kar', 'Yogi Group',
       'Uppal Group', 'Rege Group', 'Dugar Group',
       'Thakur, Shah And Pingle', 'Ganesan Ltd', 'Chhabra-Agrawal',
       'Shankar, Nadkarni And Kumer', 'Ramakrishnan, Anand And Khare',
       'Bhardwaj, Bhatia And Deshmukh', 'Ratta-Sagar', 'Chandran-Dass',
       'Mohan Group', 'Balan, Patel And Mall', 'Wali, Sood And Bala',
       'Wable, Randhawa And Mutti', 'Subramanian, Chaudhuri And Dora',
       'Hora-Roy', 'Pau And Sons', 'Gara And Sons', 'Rout-Sarna',
       'Bains, Deol And Vaidya', 'Wali, Virk And Iyer', 'Arya Group',
       'Raghavan, Magar And Shanker', 'Kala Group', 'Bora-Thakkar',
       'Banik-Ratta', 'Shetty-Bora', 'Roy-Char', 'Handa Plc',
       'Chaudhuri Plc', 'Mani Plc', 'Prasad Llc', 'Aggarwal Group',
       'Trivedi-Ahluwalia', 'Padmanabhan-Virk', 'Subramaniam Llc',
       'Lala, Kalita And Sathe', 'Gole, Chand And Dada', 'Sidhu Plc',
       'Dasgupta Plc', 'Kapadia-D’Alia', 'Chahal Group',
       'Shetty And Sons', 'Dutta Inc', 'Nagi, Sampath And Khurana',
       'Andra, Mander And Kari', 'Jha Group', 'Kadakia-Yadav',
       'Chaudhari, Pant And Singh', 'Yohannan Inc', 'Roy, Seth And Patla',
       'Goda Inc', 'Kunda, Dave And Sahni', 'Sinha, Pau And Chhabra',
       'Pradhan And Sons', 'Swaminathan, Mahal And Dara', 'Mann-Kapadia',
       'Kala-Vig', 'Chanda, Som And Vohra', 'Guha-Subramaniam',
       'Chad, Yohannan And Chopra', 'Krishnamurthy, Sibal And Das',
       'Gulati-Tandon', 'Bahl-Pau', 'Raj And Sons', 'Karpe Inc',
       'Datta Ltd', 'Jani-Ram', 'Nagar Llc', 'Taneja, Kala And Kota',
       'Mital-Oza', 'Golla-Luthra', 'D’Alia-Dey', 'Pal-Sehgal',
       'Bhasin Llc', 'Murthy-Kaul', 'Bhandari, Bhasin And Palan',
       'Sankaran, Pall And Gola', 'Hayre-Shere', 'Sastry-Issac',
       'Dass And Sons', 'Khurana-Dewan', 'Basu, Rout And Mistry',
       'Ramesh-Jain', 'Warrior, Ravel And Amble', 'Palla Llc',
       'Bhattacharyya Plc', 'Gupta Ltd', 'Karan, Bandi And Acharya',
       'Chana Llc', 'Rastogi Inc', 'Toor-Nagar', 'Baral-Kamdar',
       'Sachdev Inc', 'Dar-Kumar', 'Kothari-Datta',
       'Kara, Sodhi And Bassi', 'Mammen-Hegde',
       'Nadig, Zachariah And Soni', 'Banerjee Inc', 'Baral Group',
       'Kohli-Sawhney', 'Mohan-Virk', 'Chakrabarti-Batra',
       'Varkey, Devi And Ganguly', 'Agate Ltd', 'Agate And Sons',
       'Chauhan Inc', 'Viswanathan-Sha', 'Bhat, Nigam And Hayer',
       'Sabharwal-Mital', 'Som Inc', 'Purohit Group',
       'Ramanathan, Agarwal And Baria', 'Wable, Sankaran And Hari',
       'Bahl, Jaggi And Nath', 'Deo-Kamdar', 'Grewal, Swamy And Dayal',
       'Tella-Master', 'Cherian-Dara', 'Vaidya, Amble And Palla',
       'Nazareth Ltd', 'Balasubramanian Plc', 'Kanda-Gupta',
       'Bose-Pandit', 'Khurana And Sons', 'Raghavan Inc',
       'Deshpande-Rama', 'Gala, Magar And Rajagopal', 'Memon-Barad',
       'Rastogi Group', 'Jhaveri, Kata And Kapur', 'Nadkarni Inc',
       'Parmer, Gola And Yogi', 'Naik Ltd', 'Nadig Ltd',
       'Ghose, Ben And Divan', 'Muni-Shankar', 'Gulati, Ram And Sarkar',
       'Parikh, Oak And Kara', 'Ramesh Inc', 'Memon Ltd',
       'Borde, Peri And Upadhyay', 'Dhar Plc', 'Mangal-Sathe',
       'Barman-Ahluwalia', 'Dayal, Mammen And More', 'Lalla-Srinivasan',
       'Saha-Vora', 'Bir Plc', 'Thaman-Lanka',
       'Gaba, Sodhi And Choudhary', 'Murty, Varghese And Saxena',
       'Pall, Sule And Sood', 'Gera, Narang And Karpe', 'Keer-Gill',
       'Varkey Llc', 'Mand-Choudhry', 'Khalsa-Bhavsar', 'Dutta-Halder',
       'Batta-Doctor', 'Hans Inc', 'Edwin-Lall',
       'Arya, Sundaram And Pingle', 'Sathe, Agarwal And Dhar', 'Ben-Ravi',
       'Naidu Plc', 'Sampath, Mane And Mody',
       'Kibe, Contractor And Randhawa', 'Balan, Samra And Sekhon',
       'Munshi-Grewal', 'Sant-Mahajan', 'Roy, Barad And De', 'Kaur-Gola',
       'Kadakia, Mohan And Sathe', 'Sachdev Group',
       'Biswas, Kapoor And Patel', 'Arora Llc', 'Mitter Group',
       'Acharya Plc', 'Dalal-Shan', 'Sibal, Bhatnagar And Rajan',
       'Arora-Magar', 'Malhotra Llc', 'Shere, Thakur And Naik',
       'Mannan, Naidu And Sama', 'Barman Inc', 'Mandal Llc',
       'Balan Group', 'Balakrishnan Ltd', 'Kashyap-Reddy',
       'Ranganathan-Peri', 'Kurian, Patla And Sanghvi', 'Karnik Plc',
       'Lall Llc', 'Talwar And Sons', 'Mahal Group', 'Narula Group',
       'Garg, Saraf And Dutta', 'Morar-Mistry', 'Mallick Plc',
       'Loyal Inc', 'Dora-Pillai', 'Sehgal-Nagarajan', 'Srinivas Plc',
       'Anne, Mammen And Khatri', 'Acharya Ltd',
       'Sharma, Chandra And Prashad', 'Dubey-Sarin', 'Saini Llc',
       'Majumdar Plc', 'Balakrishnan-Kaur', 'Chauhan-Sabharwal',
       'Batta Inc', 'Krishna, Bail And Dyal', 'Shroff, Wason And Dugar',
       'Basu, Thakur And Rege', 'Parekh, Lad And Kadakia', 'Lal-Chauhan',
       'Sandal Plc', 'Narayanan-Kumar', 'Minhas, Kapoor And Sethi',
       'Doctor-Patla', 'Pillay-Ahuja', 'Dyal, Saraf And Goel',
       'Ramanathan Group', 'Mani, Dhar And Muni', 'Raja And Sons',
       'Khurana, Khosla And Yohannan', 'Lall, Datta And Swamy',
       'Batra, Sant And Mandal', 'Char-Divan', 'Savant, Batta And Mander',
       'Magar, Gara And Garg', 'Sundaram Inc', 'Sura, Pillay And Mammen',
       'Edwin And Sons', 'Apte, Soman And Raju', 'Dalal Plc',
       'Garg, Kari And Kapur', 'Gole-Doshi', 'Parsa-Bala',
       'Basu And Sons', 'Pai, Kashyap And Ramachandran', 'Shah And Sons',
       'Gaba Llc', 'Kurian-Chhabra', 'Hayer-Banerjee',
       'Barad, Devi And Andra', 'Ramanathan, Joshi And Srinivasan',
       'Prakash, Bawa And Kale', 'Pant Llc', 'Ram-Suri', 'Balan-Madan',
       'Kara-Golla'], dtype=object)

In [37]:
products["category"].unique()

array(['Fruits & Vegetables', 'Dairy & Breakfast', 'Snacks & Munchies',
       'Cold Drinks & Juices', 'Instant & Frozen Food',
       'Grocery & Staples', 'Household Care', 'Personal Care',
       'Baby Care', 'Pet Care', 'Pharmacy'], dtype=object)

In [40]:
products["category"] = products["category"].astype("category")

In [41]:
products["brand"] = products["brand"].astype("category")

In [44]:
products.head()

,product_id,product_name,category,brand,price,mrp,margin_percentage,shelf_life_days,min_stock_level,max_stock_level
0,153019,Onions,Fruits & Vegetables,Aurora Llc,947.95,1263.93,25.0,3,13,88
1,11422,Potatoes,Fruits & Vegetables,Ramaswamy-Tata,127.16,169.55,25.0,3,20,65
2,669378,Potatoes,Fruits & Vegetables,Chadha And Sons,212.14,282.85,25.0,3,23,70
3,848226,Tomatoes,Fruits & Vegetables,Barad And Sons,209.59,279.45,25.0,3,10,51
4,890623,Onions,Fruits & Vegetables,"Sangha, Nagar And Varty",354.52,472.69,25.0,3,27,55

In [45]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 268 entries, 0 to 267
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   product_id         268 non-null    int64
 1   product_name       268 non-null    object
 2   category           268 non-null    category
 3   brand              268 non-null    category
 4   price              268 non-null    float64
 5   mrp                268 non-null    float64
 6   margin_percentage  268 non-null    float64
 7   shelf_life_days    268 non-null    int64
 8   min_stock_level    268 non-null    int64
 9   max_stock_level    268 non-null    int64
dtypes: category(2), float64(3), int64(4), object(1)
memory usage: 28.2+ KB

In [57]:
products.to_csv(
    "cleaned_products.csv",
    index=False
)

# Order Items Table Analysis

In [46]:
order_items.head()

     order_id  product_id  quantity  unit_price
0  1961864118      642612         3      517.03
1  1549769649      378676         1      881.42
2  9185164487      741341         2      923.84
3  9644738826      561860         1      874.78
4  5427684290      602241         2      976.55

In [47]:
order_items.isnull().sum()

order_id      0
product_id    0
quantity      0
unit_price    0
dtype: int64

In [48]:
order_items.drop_duplicates(inplace=True)

In [49]:
order_items[
    order_items.duplicated(
        subset=["order_id","product_id"],
        keep=False
    )
]

Empty DataFrame
Columns: [order_id, product_id, quantity, unit_price]
Index: []

In [50]:
order_items.dtypes

order_id        int64
product_id      int64
quantity        int64
unit_price    float64
dtype: object

In [51]:
order_items["order_id"].isin(
    orders["order_id"]
).all()

True

In [52]:
order_items["product_id"].isin(
    products["product_id"]
).all()

True

In [53]:
order_items["sales"] = (
    order_items["quantity"] *
    order_items["unit_price"]
)

In [54]:
order_items["average_selling_price"] = (
    order_items["sales"] /
    order_items["quantity"]
)

In [58]:
order_items.to_csv(
    "cleaned_order_items.csv",
    index=False
)

# Inventory Table Analysis

In [59]:
order_items.to_csv(
    "cleaned_order_items.csv",
    index=False
)

In [60]:
inventory.isnull().sum()

product_id        0
date              0
stock_received    0
damaged_stock     0
dtype: int64

In [61]:
inventory.drop_duplicates(inplace=True)

In [62]:
inventory.duplicated(
    subset=["product_id","date"]
).sum()

0

In [63]:
inventory.dtypes

product_id         int64
date              object
stock_received     int64
damaged_stock      int64
dtype: object

In [65]:
inventory["date"] = pd.to_datetime(
    inventory["date"],
    dayfirst=True,
    errors="coerce"
)

In [66]:
inventory["month"] = inventory["date"].dt.month_name()
inventory["year"] = inventory["date"].dt.year

In [67]:
inventory_products = inventory.merge(
    products[
        [
            "product_id",
            "product_name",
            "category"
        ]
    ],
    on="product_id",
    how="left"
)

In [68]:
inventory.head()

   product_id       date  stock_received  damaged_stock  month  year
0      153019 2023-03-17               4              2  March  2023
1      848226 2023-03-17               4              2  March  2023
2      965755 2023-03-17               1              0  March  2023
3       39154 2023-03-17               4              0  March  2023
4       34186 2023-03-17               3              2  March  2023

In [69]:
inventory.to_csv(
    "cleaned_inventory.csv",
    index=False
)

# Delievery Table Analysis

In [70]:
delivery.head()

,order_id,delivery_partner_id,promised_time,actual_time,delivery_time_minutes,distance_km,delivery_status,reasons_if_delayed
0,1961864118,63230,2024-07-17 08:52:01,2024-07-17 08:47:01,-5.0,0.96,On Time,NaN
1,1549769649,14983,2024-05-28 13:25:29,2024-05-28 13:27:29,2.0,0.98,On Time,Traffic
2,9185164487,39859,2024-09-23 13:25:12,2024-09-23 13:29:12,4.0,3.83,On Time,Traffic
3,9644738826,61497,2023-11-24 16:34:56,2023-11-24 16:33:56,-1.0,2.76,On Time,NaN
4,5427684290,84315,2023-11-20 05:17:39,2023-11-20 05:18:39,1.0,2.63,On Time,Traffic

In [71]:
delivery.isnull().sum()

order_id                    0
delivery_partner_id         0
promised_time               0
actual_time                 0
delivery_time_minutes       0
distance_km                 0
delivery_status             0
reasons_if_delayed       1902
dtype: int64

In [72]:
delivery.drop_duplicates(inplace=True)

In [73]:
delivery[
    delivery["order_id"].duplicated(keep=False)
]

Empty DataFrame
Columns: [order_id, delivery_partner_id, promised_time, actual_time, delivery_time_minutes, distance_km, delivery_status, reasons_if_delayed]
Index: []

In [74]:
delivery["promised_time"] = pd.to_datetime(
    delivery["promised_time"],
    errors="coerce"
)

delivery["actual_time"] = pd.to_datetime(
    delivery["actual_time"],
    errors="coerce"
)

In [75]:
delivery.dtypes

order_id                          int64
delivery_partner_id               int64
promised_time            datetime64[ns]
actual_time              datetime64[ns]
delivery_time_minutes           float64
distance_km                     float64
delivery_status                  object
reasons_if_delayed               object
dtype: object

In [76]:
delivery["delivery_status"] = (
    delivery["delivery_status"]
    .str.strip()
    .str.title()
)

delivery["reasons_if_delayed"] = (
    delivery["reasons_if_delayed"]
    .fillna("No Delay")
    .str.strip()
    .str.title()
)

In [77]:
delivery_check = delivery.merge(
    orders[["order_id","order_date"]],
    on="order_id",
    how="left"
)

In [78]:
delivery["order_id"].isin(
    orders["order_id"]
).all()

True

In [79]:
delivery.to_csv(
    "cleaned_delivery_performance.csv",
    index=False
)

# Feedback Table Analysis

In [80]:
feedback.head()

,feedback_id,order_id,customer_id,rating,feedback_text,feedback_category,sentiment,feedback_date
0,2234710,1961864118,30065862,4,"It was okay, nothing special.",Delivery,Neutral,2024-07-17
1,5450964,1549769649,9573071,3,The order was incorrect.,App Experience,Negative,2024-05-28
2,482108,9185164487,45477575,3,"It was okay, nothing special.",App Experience,Neutral,2024-09-23
3,4823104,9644738826,88067569,4,The product met my expectations.,App Experience,Neutral,2023-11-24
4,3537464,5427684290,83298567,3,Product was damaged during delivery.,Delivery,Negative,2023-11-20

In [81]:
feedback.isnull().sum()

feedback_id          0
order_id             0
customer_id          0
rating               0
feedback_text        0
feedback_category    0
sentiment            0
feedback_date        0
dtype: int64

In [82]:
feedback.drop_duplicates(inplace=True)

In [83]:
feedback["feedback_id"].is_unique

True

In [84]:
feedback["feedback_date"] = pd.to_datetime(
    feedback["feedback_date"],
    errors="coerce"
)

In [85]:
text_columns = [
    "feedback_text",
    "feedback_category",
    "sentiment"
]

for col in text_columns:
    feedback[col] = feedback[col].str.strip()

In [86]:
feedback["feedback_category"] = feedback["feedback_category"].astype("category")

feedback["sentiment"] = feedback["sentiment"].astype("category")

In [87]:
feedback["order_id"].isin(
    orders["order_id"]
).all()

True

In [88]:
feedback["customer_id"].isin(
    customers["customer_id"]
).all()

True

In [89]:
feedback["feedback_month"] = feedback["feedback_date"].dt.month_name()

In [90]:
feedback["feedback_year"] = feedback["feedback_date"].dt.year

In [91]:
feedback_orders = feedback.merge(
    orders[
        ["order_id", "payment_method", "order_total"]
    ],
    on="order_id",
    how="left"
)

In [93]:
feedback_delivery = feedback.merge(
    delivery[
        ["order_id"]
    ],
    on="order_id",
    how="left"
)

In [94]:
feedback.to_csv(
    "cleaned_customer_feedback.csv",
    index=False
)

# Marketing Table Analysis

In [95]:
marketing.head()

,campaign_id,campaign_name,date,target_audience,channel,impressions,clicks,conversions,spend,revenue_generated,roas
0,548299,New User Discount,2024-11-05,Premium,App,3130,163,78,1431.85,4777.75,3.60
1,390914,Weekend Special,2024-11-05,Inactive,App,3925,494,45,4506.34,6238.11,2.98
2,834385,Festival Offer,2024-11-05,Inactive,Email,7012,370,78,4524.23,2621.00,2.95
3,241523,Flash Sale,2024-11-05,Inactive,SMS,1115,579,86,3622.79,2955.00,2.84
4,595111,Membership Drive,2024-11-05,New Users,Email,7172,795,54,2888.99,8951.81,2.22

In [96]:
marketing.isnull().sum()

campaign_id          0
campaign_name        0
date                 0
target_audience      0
channel              0
impressions          0
clicks               0
conversions          0
spend                0
revenue_generated    0
roas                 0
dtype: int64

In [97]:
marketing.drop_duplicates(inplace=True)

In [98]:
marketing["campaign_id"].is_unique

True

In [99]:
marketing["date"] = pd.to_datetime(
    marketing["date"],
    format="%d-%m-%Y",
    errors="coerce"
)

In [100]:
marketing.dtypes

campaign_id                   int64
campaign_name                object
date                 datetime64[ns]
target_audience              object
channel                      object
impressions                   int64
clicks                        int64
conversions                   int64
spend                       float64
revenue_generated           float64
roas                        float64
dtype: object

In [101]:
text_cols = [
    "campaign_name",
    "target_audience",
    "channel"
]

for col in text_cols:
    marketing[col] = marketing[col].str.strip().str.title()

In [102]:
marketing["month"] = marketing["date"].dt.month_name()

In [103]:
marketing["year"] = marketing["date"].dt.year

In [104]:
marketing.to_csv(
    "cleaned_marketing.csv",
    index=False
)

# Data Integration

In [106]:
# ================================
# Customer Analysis Dataset
# ================================

customer_analysis = (
    customers
    .merge(orders, on="customer_id", how="left")
    .merge(
        feedback[
            ["order_id","rating","sentiment","feedback_category"]
        ],
        on="order_id",
        how="left"
    )
)

# ================================
# Sales Analysis Dataset
# ================================

sales_analysis = (
    orders
    .merge(order_items, on="order_id", how="left")
    .merge(products, on="product_id", how="left")
    .merge(
        customers[
            ["customer_id","customer_name","customer_segment"]
        ],
        on="customer_id",
        how="left"
    )
)

# ================================
# Product Analysis Dataset
# ================================

product_analysis = (
    order_items
    .merge(products, on="product_id", how="left")
)

# ================================
# Inventory Analysis Dataset
# ================================

inventory_analysis = (
    inventory
    .merge(products, on="product_id", how="left")
)

# ================================
# Delivery Analysis Dataset
# ================================

delivery_analysis = (
    delivery
    .merge(orders, on="order_id", how="left")
    .merge(
        feedback[
            ["order_id","rating","sentiment","feedback_category"]
        ],
        on="order_id",
        how="left"
    )
)

# ================================
# Marketing Analysis Dataset
# ================================

marketing_analysis = marketing.copy()

# ================================
# Master Dataset
# ================================

master = (
    orders
    .merge(customers, on="customer_id", how="left")
    .merge(order_items, on="order_id", how="left")
    .merge(products, on="product_id", how="left")
    .merge(delivery, on="order_id", how="left")
    .merge(feedback, on=["order_id","customer_id"], how="left")
)

# Export Final Clean Data

In [107]:
master.to_csv("master_dataset.csv", index=False)

customer_analysis.to_csv("customer_analysis.csv", index=False)

sales_analysis.to_csv("sales_analysis.csv", index=False)

product_analysis.to_csv("product_analysis.csv", index=False)

inventory_analysis.to_csv("inventory_analysis.csv", index=False)

delivery_analysis.to_csv("delivery_analysis.csv", index=False)

marketing_analysis.to_csv("marketing_analysis.csv", index=False)